//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string TableName { get; set; }
        public string Action { get; set; }
        public string Data { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ReviewedBy { get; set; }
        public Nullable<System.DateTime> DateReviewed { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public string CreatedByUsername { get; set; }
        public string ReviewedByUsername { get; set; }
        public string ApprovedByUsername { get; set; }
    }
}
