//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory()
        {
            this.Carts = new HashSet<Cart>();
            this.Inventory_Count = new HashSet<Inventory_Count>();
        }
    
        public int Id { get; set; }
        public byte[] Image { get; set; }
        public string Name { get; set; }
        public string SetCode { get; set; }
        public string SetName { get; set; }
        public string Collector { get; set; }
        public string FoilType { get; set; }
        public string Rarity { get; set; }
        public int ManaboxId { get; set; }
        public string ScryfallId { get; set; }
        public decimal Price { get; set; }
        public bool Misprint { get; set; }
        public bool Tampered { get; set; }
        public string Condition { get; set; }
        public string Language { get; set; }
        public string PurchaseCurrency { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public string Description { get; set; }
        public string Color { get; set; }
        public string ManaCost { get; set; }
        public string CardType { get; set; }
        public string IllustratedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_Count> Inventory_Count { get; set; }
    }
}
