//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Count
    {
        public int Id { get; set; }
        public int InventoryId { get; set; }
        public decimal Quantity { get; set; }
        public string UOM { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int Type { get; set; }
        public string CreatedBy { get; set; }
        public string Remarks { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Inventory Inventory { get; set; }
    }
}
