//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_Item = new HashSet<Order_Item>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string OrderNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public string CustomerName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string ContactNumber { get; set; }
        public string ContactEmail { get; set; }
        public int PaymentMethod { get; set; }
        public decimal SubTotal { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Shipping { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string BookAccountNumber { get; set; }
        public int Status { get; set; }
        public int DeliveryStatus { get; set; }
        public int DeliveryMethod { get; set; }
        public string DeliveryNote { get; set; }
        public string Currency { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Item> Order_Item { get; set; }
    }
}
