//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_WebsiteInfo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string LongName { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string ContactNumber1 { get; set; }
        public string ContactNumber2 { get; set; }
        public string ContactEmail1 { get; set; }
        public string ContactEmail2 { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string WorkingHour { get; set; }
        public string FB { get; set; }
        public string Insta { get; set; }
        public string Twitter { get; set; }
        public string LinkeIn { get; set; }
    }
}
