//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Session
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Token { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime LastDateOfActivity { get; set; }
        public bool IsTerminated { get; set; }
        public string IPAddress { get; set; }
        public string FullName { get; set; }
    }
}
