INSERT INTO [IMS].[dbo].[Setting_Group] ([Name], [DateCreated], [IsDeleted])
VALUES
('Lorwyn Eclipsed', GETDATE(), 0),
('Avatar: The Last Airbender', GETDATE(), 0),
('Marvel''s Spider-Man', GETDATE(), 0),
('Through the Omenpaths', GETDATE(), 0),
('Edge of Eternities', GETDATE(), 0),
('Final Fantasy', GETDATE(), 0),
('Tarkir: Dragonstorm', GETDATE(), 0),
('Aetherdrift', GETDATE(), 0),
('Innistrad Remastered', GETDATE(), 0),
('Pioneer Masters', GETDATE(), 0),
('Foundations', GETDATE(), 0),
('Foundations Jumpstart', GETDATE(), 0),
('Duskmourn: House of Horror', GETDATE(), 0),
('Mystery Booster 2', GETDATE(), 0),
('Bloomburrow', GETDATE(), 0),
('Assassin''s Creed', GETDATE(), 0),
('Modern Horizons 3', GETDATE(), 0),
('Modern Horizons 2 Timeshifts', GETDATE(), 0),
('The Big Score', GETDATE(), 0),
('Outlaws of Thunder Junction', GETDATE(), 0),
('Ravnica: Clue Edition', GETDATE(), 0),
('Murders at Karlov Manor', GETDATE(), 0),
('Ravnica Remastered', GETDATE(), 0),
('The Lost Caverns of Ixalan', GETDATE(), 0),
('Wilds of Eldraine', GETDATE(), 0),
('Commander Masters', GETDATE(), 0),
('The Lord of the Rings: Tales of Middle-earth', GETDATE(), 0),
('March of the Machine: The Aftermath', GETDATE(), 0),
('March of the Machine', GETDATE(), 0),
('Shadows of the Past', GETDATE(), 0),
('Shadows over Innistrad Remastered', GETDATE(), 0),
('Phyrexia: All Will Be One', GETDATE(), 0),
('Dominaria Remastered', GETDATE(), 0),
('Jumpstart 2022', GETDATE(), 0),
('The Brothers'' War', GETDATE(), 0),
('Dominaria United', GETDATE(), 0),
('Double Masters 2022', GETDATE(), 0),
('Commander Legends: Battle for Baldur''s Gate', GETDATE(), 0),
('Streets of New Capenna', GETDATE(), 0),
('Universes Within', GETDATE(), 0),
('Kamigawa: Neon Dynasty', GETDATE(), 0),
('Innistrad: Double Feature', GETDATE(), 0),
('Innistrad: Crimson Vow', GETDATE(), 0),
('Innistrad: Midnight Hunt', GETDATE(), 0),
('Jumpstart: Historic Horizons', GETDATE(), 0),
('Adventures in the Forgotten Realms', GETDATE(), 0),
('Modern Horizons 2', GETDATE(), 0),
('Modern Horizons 1 Timeshifts', GETDATE(), 0),
('Strixhaven: School of Mages', GETDATE(), 0),
('Time Spiral Remastered', GETDATE(), 0),
('Kaldheim', GETDATE(), 0),
('Commander Legends', GETDATE(), 0),
('Kaladesh Remastered', GETDATE(), 0),
('The List', GETDATE(), 0),
('Zendikar Rising', GETDATE(), 0),
('Amonkhet Remastered', GETDATE(), 0),
('Double Masters', GETDATE(), 0),
('Jumpstart', GETDATE(), 0),
('Core Set 2021', GETDATE(), 0),
('Ikoria: Lair of Behemoths', GETDATE(), 0),
('Theros Beyond Death', GETDATE(), 0),
('Throne of Eldraine', GETDATE(), 0),
('Core Set 2020', GETDATE(), 0),
('Modern Horizons', GETDATE(), 0),
('War of the Spark', GETDATE(), 0),
('Ravnica Allegiance', GETDATE(), 0),
('Ultimate Masters', GETDATE(), 0),
('Guilds of Ravnica', GETDATE(), 0),
('Core Set 2019', GETDATE(), 0),
('Battlebond', GETDATE(), 0),
('Dominaria', GETDATE(), 0),
('Masters 25', GETDATE(), 0),
('Rivals of Ixalan', GETDATE(), 0),
('Iconic Masters', GETDATE(), 0),
('Ixalan', GETDATE(), 0),
('Hour of Devastation', GETDATE(), 0),
('Amonkhet', GETDATE(), 0),
('Modern Masters 2017', GETDATE(), 0),
('Aether Revolt', GETDATE(), 0),
('Kaladesh', GETDATE(), 0),
('Conspiracy: Take the Crown', GETDATE(), 0),
('Eldritch Moon', GETDATE(), 0),
('Eternal Masters', GETDATE(), 0),
('Shadows over Innistrad', GETDATE(), 0),
('Oath of the Gatewatch', GETDATE(), 0),
('Battle for Zendikar', GETDATE(), 0),
('Magic Origins', GETDATE(), 0),
('Modern Masters 2015', GETDATE(), 0),
('Tempest Remastered', GETDATE(), 0),
('Dragons of Tarkir', GETDATE(), 0),
('Fate Reforged', GETDATE(), 0),
('Khans of Tarkir', GETDATE(), 0),
('Magic 2015', GETDATE(), 0),
('Vintage Masters', GETDATE(), 0),
('Conspiracy', GETDATE(), 0),
('Journey into Nyx', GETDATE(), 0),
('Born of the Gods', GETDATE(), 0),
('Theros', GETDATE(), 0),
('Magic 2014', GETDATE(), 0),
('Modern Masters', GETDATE(), 0),
('Dragon''s Maze', GETDATE(), 0),
('Gatecrash', GETDATE(), 0),
('Return to Ravnica', GETDATE(), 0),
('Magic 2013', GETDATE(), 0),
('Avacyn Restored', GETDATE(), 0),
('Dark Ascension', GETDATE(), 0),
('Innistrad', GETDATE(), 0),
('Magic 2012', GETDATE(), 0),
('New Phyrexia', GETDATE(), 0),
('Mirrodin Besieged', GETDATE(), 0),
('Masters Edition IV', GETDATE(), 0),
('Scars of Mirrodin', GETDATE(), 0),
('Magic 2011', GETDATE(), 0),
('Rise of the Eldrazi', GETDATE(), 0),
('Worldwake', GETDATE(), 0),
('Zendikar', GETDATE(), 0),
('Masters Edition III', GETDATE(), 0),
('Magic 2010', GETDATE(), 0),
('Alara Reborn', GETDATE(), 0),
('Conflux', GETDATE(), 0),
('Shards of Alara', GETDATE(), 0),
('Masters Edition II', GETDATE(), 0),
('Eventide', GETDATE(), 0),
('Shadowmoor', GETDATE(), 0),
('Morningtide', GETDATE(), 0),
('Lorwyn', GETDATE(), 0),
('Masters Edition', GETDATE(), 0),
('Tenth Edition', GETDATE(), 0),
('Future Sight', GETDATE(), 0),
('Planar Chaos', GETDATE(), 0),
('Time Spiral Timeshifted', GETDATE(), 0),
('Time Spiral', GETDATE(), 0),
('Coldsnap', GETDATE(), 0),
('Dissension', GETDATE(), 0),
('Guildpact', GETDATE(), 0),
('Ravnica: City of Guilds', GETDATE(), 0),
('Ninth Edition', GETDATE(), 0),
('Saviors of Kamigawa', GETDATE(), 0),
('Betrayers of Kamigawa', GETDATE(), 0),
('Champions of Kamigawa', GETDATE(), 0),
('Fifth Dawn', GETDATE(), 0),
('Darksteel', GETDATE(), 0),
('Mirrodin', GETDATE(), 0),
('Eighth Edition', GETDATE(), 0),
('Scourge', GETDATE(), 0),
('Legions', GETDATE(), 0),
('Onslaught', GETDATE(), 0),
('Judgment', GETDATE(), 0),
('Torment', GETDATE(), 0),
('Odyssey', GETDATE(), 0),
('Apocalypse', GETDATE(), 0),
('Seventh Edition', GETDATE(), 0),
('Planeshift', GETDATE(), 0),
('Invasion', GETDATE(), 0),
('Prophecy', GETDATE(), 0),
('Nemesis', GETDATE(), 0),
('Mercadian Masques', GETDATE(), 0),
('Urza''s Destiny', GETDATE(), 0),
('Classic Sixth Edition', GETDATE(), 0),
('Urza''s Legacy', GETDATE(), 0),
('Urza''s Saga', GETDATE(), 0),
('Exodus', GETDATE(), 0),
('Stronghold', GETDATE(), 0),
('Tempest', GETDATE(), 0),
('Weatherlight', GETDATE(), 0),
('Fifth Edition', GETDATE(), 0),
('Visions', GETDATE(), 0),
('Mirage', GETDATE(), 0),
('Alliances', GETDATE(), 0),
('Homelands', GETDATE(), 0),
('Rinascimento', GETDATE(), 0),
('Renaissance', GETDATE(), 0),
('Chronicles', GETDATE(), 0),
('Chronicles Foreign Black Border', GETDATE(), 0),
('Ice Age', GETDATE(), 0),
('Fourth Edition Foreign Black Border', GETDATE(), 0),
('Fourth Edition', GETDATE(), 0),
('Fallen Empires', GETDATE(), 0),
('The Dark', GETDATE(), 0),
('Summer Magic / Edgar', GETDATE(), 0),
('Legends', GETDATE(), 0),
('Foreign Black Border', GETDATE(), 0),
('Revised Edition', GETDATE(), 0),
('Antiquities', GETDATE(), 0),
('Arabian Nights', GETDATE(), 0),
('Unlimited Edition', GETDATE(), 0),
('Limited Edition Beta', GETDATE(), 0),
('Limited Edition Alpha', GETDATE(), 0);
